
project_id = "aysvkiyuzqktcumdzxqh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_minimal_signup = true

# Enable Google OAuth authentication
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

# Configure edge functions
[functions]
[functions.chat-assistant]
verify_jwt = false
[functions.create-storage-buckets]
verify_jwt = false

[storage]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328

[experimental]
events_enabled = true

[[auth.cors]]
origin = "*"
methods = ["GET", "POST"]
headers = ["authorization", "apikey"]
allow_credentials = true
max_age = 3600
