
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase-types';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/lib/constants';

// Initialize the Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    // Explicitly set storage to use localStorage for web environments
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    // Ensure debug is enabled to help troubleshoot auth issues
    debug: true
  }
});

// Log initialization for debugging
console.log("Supabase client initialized with URL:", SUPABASE_URL);

// Export a function to handle bulk import of scholarships
export async function bulkImportScholarships(scholarships) {
  try {
    const { data, error } = await supabase
      .from('scholarships')
      .upsert(scholarships, { 
        onConflict: 'id',
        ignoreDuplicates: false
      });
    
    if (error) throw error;
    return { success: true, data };
  } catch (error) {
    console.error("Error importing scholarships:", error);
    return { success: false, error };
  }
}
